# Describes the format for available zhaws services

clear_lock_user_code:
  name: Clear lock user
  description: Clear a user code from a lock
  target:
    entity:
      domain: lock
      integration: zha
  fields:
    code_slot:
      name: Code slot
      description: Code slot to clear code from
      required: true
      example: 1
      selector:
        text:

enable_lock_user_code:
  name: Enable lock user
  description: Enable a user code on a lock
  target:
    entity:
      domain: lock
      integration: zha
  fields:
    code_slot:
      name: Code slot
      description: Code slot to enable
      required: true
      example: 1
      selector:
        text:

disable_lock_user_code:
  name: Disable lock user
  description: Disable a user code on a lock
  target:
    entity:
      domain: lock
      integration: zha
  fields:
    code_slot:
      name: Code slot
      description: Code slot to disable
      required: true
      example: 1
      selector:
        text:

set_lock_user_code:
  name: Set lock user code
  description: Set a user code on a lock
  target:
    entity:
      domain: lock
      integration: zha
  fields:
    code_slot:
      name: Code slot
      description: Code slot to set the code in
      required: true
      example: 1
      selector:
        text:
    user_code:
      name: Code
      description: Code to set
      required: true
      example: 1234
      selector:
        text:
